### ISSUE TITLE
Logs not working

### ISSUE THREAD

**Issue by LindsayCole** [sgu222e/pleximusmaximus#4]
When I create an "intervention required" situation, the folder it rights the logs to appears, but does not write a log.

**Comment by sgu222e** [comment]
Updated code to create fail.log in consistant place

**Comment by LindsayCole** [comment]
Folder is no longer being created.

Logs are not time stamped- 
Plex Media Server not running

Appears in the logs multiple times.

Might not be horrible to say what was detected as failing (web/server component) and log that as well.

**Comment by sgu222e** [comment]
modified and retested script locally
- Folder gets created
- Log file gets timesatmp: failDATE-TIMESTAMP.log
- Time stamp also echoed into the log file, with failure reason (Plex Server EXE not responding/Plex Web App not responding)
NOTE: Time stamp is HHMMSS (095132)

**Comment by LindsayCole** [comment]
This works properly now. :) You can close.
