### ISSUE TITLE
Give output to task scheduler

### ISSUE THREAD

**Issue by LindsayCole** [sgu222e/pleximusmaximus#5]
Currently, we rely on Task Scheduler for normal operation.

Task scheduler looks for a a conditional response code of some sort (beyond my understanding). As of right now, success or fail, it returns a 0xFF code. Which is essentially "I don't know"- so if you look into scheduler, it doesn't know if it failed or not. 

Looks like there might be an exit code that can be added.

**Comment by sgu222e** [comment]
Added exit code and additional end conditions, will need testing

**Comment by LindsayCole** [comment]
Unfortunately, no change.

**Comment by sgu222e** [comment]
Tested Task Scheduler with outputs in script
0x0 = All Good
0x1 = Something failed last run
0x9 = Something really bad happened, I couldn't even test the EXE or Web App (Hopefully you don't this one)

**Comment by LindsayCole** [comment]
Confirmed that this is working perfect.
